// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snyjdceftzcdyxkfweem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNueWpkY2VmdHpjZHl4a2Z3ZWVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NTQ1ODksImV4cCI6MjA2MDMzMDU4OX0.iigbYDTMjPrn0Pd4AOeLoy9umImkdgGOQaQME9dKNH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);